package engine;

public enum CommandType {
    END, INVENTORY, NORD, SOUTH, EAST, WEST, SOUTH_WEST, SOUTH_EAST, NORTH_EAST, NORTH_WEST, UP, DOWN, OPEN, CLOSE, PUSH, PULL, WALK_TO, PICK_UP, TALK_TO, GIVE, USE, LOOK_AT, TURN_ON, TURN_OFF, DROP, BREAK
}
